### ISSUE TITLE
Getting error while running the HAR file using CLI

### ISSUE THREAD

**Issue by akshamat** [zalando-incubator/transformer#74] opened 2021-03-08 10:27 UTC
**Describe the bug**

I am getting below error so code is not able to convert into Locust python file
WARNING while searching for HAR files, skipping C:\HAR_File\demoblaze.com.har: 'charmap' codec can't decode byte 0x8d in position 219193: character maps to <undefined>
2021-03-08 15:40:33,826 ERROR   Please help us fix this error by reporting it! https://github.com/zalando-incubator/Transformer/issues

**Transformer version**
1.3.0

**To Reproduce**
Steps and input files to reproduce the behavior:
1. https://www.demoblaze.com/
2. Use Google Chrome to capture network traffic
3. Export the har file
4.  I used following command **transformer C:\HAR_File/ >locustfile.py** on windows command prompt
5. ![image](https://user-images.githubusercontent.com/46412740/110308768-872e4080-8026-11eb-82cf-914b1d076235.png)

**Expected behavior**
It should create locustfile.py successfully without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/46412740/110308838-9f9e5b00-8026-11eb-9a8f-09fd472abc8c.png)

**Desktop (please complete the following information):**
 - OS: Windows Command

**Additional context**

**Comment by thilp** [comment] 2021-03-12 16:52
Hi, this looks like a duplicate of #72 (based on the first line of your error message, only partially visible in your screenshot). Unfortunately, this project currently doesn’t have the resources to support Windows as a first-class platform. Please try running Transformer inside Docker instead!

**Closed by thilp** 2021-03-12 16:52 UTC
Labels: bug

**Comment by JustinRoll** [comment] 2021-10-20 23:17
Hey all, 
I had a similar issue, and found that if you just pre-process the file and re-encode it in python, you can get it to run.

_f1Text = open('har/login.har', encoding='utf-8').read()
newText = f1Text.encode('charmap', errors='ignore').decode('charmap')
newOut = open('har/login_new.har', 'w', encoding = 'charmap')
newOut.write(newText)

#now run transformer on your har directory_

It could be nice to just detect if you're on windows and use a different encoding by default though.

**Comment by maormagori** [comment] 2022-01-16 12:42
> Hi, this looks like a duplicate of #72 (based on the first line of your error message, only partially visible in your screenshot). Unfortunately, this project currently doesn’t have the resources to support Windows as a first-class platform. Please try running Transformer inside Docker instead!

It wasn't mentioned anywhere that Windows isn't supported.
This should be acknowledged somewhere in the README.

**Comment by thilp** [comment] 2022-04-29 17:42
I have released [v2.0.0](https://github.com/zalando-incubator/transformer/releases/tag/v2.0.0) (major version bump because I also renamed the "blacklist" keyword argument) and also uploaded it to PyPI. Please let me know if a similar problem still occurs. :slightly_smiling_face:
